version: '3'

services:
  irpf:
    build: .
    image: skarllot/irpf:2022.1.1
    environment:
      - DISPLAY=$DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/ProgramasRFB:/home/irpf/ProgramasRFB

  irpf-selinux:
    build: .
    image: skarllot/irpf:2022.1.1
    environment:
      - DISPLAY=$DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/ProgramasRFB:/home/irpf/ProgramasRFB
    security_opt:
      - label=type:container_runtime_t

